name: Run linters

on: [push]

jobs:
  linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install
      - name: ESlint
        run: npm run eslint
      - name: Commitlint
        uses: wagoid/commitlint-github-action@v6
        with:
          configFile: "./config/commitlint.config.mjs"
      - name: Markdownlint
        run: npm run markdownlint
