name: Release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
      - name: Install dependencies
        run: npm install --no-optional
      - name: Run tests
        run: xvfb-run -a npm test
      - name: Package vsce
        run: npm run package
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          prerelease: true
          files: vscode-ui5-api-reference-*.vsix
