name: Main

on:
  push:
    tags:
      - "v*.*.*"
  workflow_run:
    workflows: [Build]
    types:
      - completed

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          prerelease: true
          files: vscode-ui5-api-reference-${{ github.ref_name }}.vsix
